[package]
name = "trusted-repos-policy"
version = "0.1.6"
authors = ["Rafael Fernández López <ereslibre@ereslibre.es>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
kubewarden-policy-sdk = "0.6.2"
url = "2.2.2"
regex = "1.6.0"
