[package]
name = "trusted-repos-policy"
version = "0.1.6"
authors = ["Rafael Fernández López <ereslibre@ereslibre.es>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
k8s-openapi = { version = "0.17.0", features = ["v1_24"] }
kubewarden-policy-sdk = "0.8.6"
url = "2.3.1"
regex = "1.7.1"
