[package]
name = "trusted-repos-policy"
version = "0.1.12"
authors = ["Rafael Fernández López <ereslibre@ereslibre.es>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
k8s-openapi = { version = "0.19.0", features = ["v1_27"] }
kubewarden-policy-sdk = { version = "0.9.7", default-features = false }
url = "2.4.1"
regex = "1.9.4"
