[package]
name = "trusted-repos-policy"
version = "0.1.11"
authors = ["Rafael Fernández López <ereslibre@ereslibre.es>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
k8s-openapi = { version = "0.18.0", features = ["v1_24"] }
kubewarden-policy-sdk = "0.9.4"
url = "2.4.0"
regex = "1.9.1"
